#!/bin/bash

set -xe

source inc/common

juju-log "Configure the right APT sources."
add-apt-repository ppa:charmers/charm-helpers -y
apt-get update

juju-log "Installing tools like Wget, Git, Vim."
apt-get -y install wget git-core git-flow curl vim rsync sysstat mailutils charm-helper-sh mktemp aptitude nfs-common make

modprobe nfs || true

# PHP-FPM: Install.
juju-log "Installing PHP-FPM v5.3 (D7 uses v5.3 till now)."
apt-get -y install php5-fpm php5-cli php5-gd php5-mysql php5-mcrypt php-pear php-apc php5-curl php5-xdebug php-mail
rsync -az /var/lib/php5 /mnt/ && rm -rf /var/lib/php5 && ln -s /mnt/php5 /var/lib/

# PHP-FPM: Configure.
juju-log "Download Perusio Confs and configure PHP-FPM via socket."
git clone https://github.com/perusio/php-fpm-example-config -b unix /opt/php-fpm-example-config
mv /etc/php5/fpm/php-fpm.conf /etc/php5/fpm/php-fpm.conf_default
mv /etc/php5/fpm/php.ini /etc/php5/fpm/php.ini_default
cp /opt/php-fpm-example-config/fpm/php5-fpm.conf /etc/php5/fpm/php-fpm.conf
cp /opt/php-fpm-example-config/fpm/php.ini /etc/php5/fpm/
cp -a /opt/php-fpm-example-config/fpm/pool.d /etc/php5/fpm/

# Nginx: install.
juju-log "Download, compile and install Nginx with all the extra modules like Upload Progress."
apt-get -y install libpcre3-dev libssl-dev zlib1g-dev
curl http://nginx.org/download/nginx-1.4.1.tar.gz | tar -C /opt -zx
mv /opt/nginx-1.4.1 /opt/nginx
mkdir /opt/nginx/modules
git clone https://github.com/masterzen/nginx-upload-progress-module.git /opt/nginx/modules/nginx-upload-progress-module
git clone https://github.com/gnosek/nginx-upstream-fair /opt/nginx/modules/nginx-upstream-fair
git clone https://github.com/FRiCKLE/ngx_cache_purge.git /opt/nginx/modules/ngx_cache_purge
cd /opt/nginx; ./configure --conf-path=/etc/nginx/nginx.conf --user=www-data --group=www-data --with-http_realip_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_ssl_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --without-mail_pop3_module --without-mail_imap_module --without-http_scgi_module --without-http_uwsgi_module --with-ipv6 --with-debug --add-module=modules/nginx-upload-progress-module --add-module=modules/nginx-upstream-fair --add-module=modules/ngx_cache_purge --with-file-aio --pid-path=/var/run/nginx.pid
mkdir -p /var/cache/nginx/microcache
mkdir -p /var/log/nginx
juju-log "Installing Nginx"
cd /opt/nginx; make && make install

# Nginx: Init script.
juju-log "Nginx as a service. (service nginx start/stop)"
wget https://raw.github.com/sebas5384/nginx-init-ubuntu/master/nginx -O /etc/init.d/nginx
chmod +x /etc/init.d/nginx
update-rc.d -f nginx defaults

juju-log "Making Nginx and PHP Cache dir ..."
mkdir -p /mnt/cache/nginx/microcache
chmod -R 1777 /mnt/cache/nginx/microcache
rsync -az /var/cache/nginx/microcache /mnt/cache/nginx/microcache && rm -rf /var/cache/nginx/microcache && ln -s /mnt/cache/nginx/microcache /var/cache/nginx/microcache

juju-log "Making /mnt/logs dir ..."
mkdir -p /mnt/logs
chmod -R 1777 /mnt/logs

# Nginx: Link logs to mounted dir.
mkdir /mnt/logs/nginx && rsync -az /var/log/nginx /mnt/logs/nginx
rm -rf /var/log/nginx && ln -s /mnt/logs/nginx /var/log/nginx
# PHP-FPM: Link logs to mounted dir.
cp /var/log/php5-fpm.log /mnt/logs/php5-fpm.log && rm -rf /var/log/php5-fpm.log && ln -s /mnt/logs/php5-fpm.log /var/log/php5-fpm.log

juju-log "Making /mnt/tmp dir ..."
mkdir -p /mnt/tmp
chmod 1777 /mnt/tmp

# OS staff: User ubuntu in www-data group.
juju-log "Adding ubuntu user in the www-data group."
usermod -a -G www-data ubuntu

# Composer: install.
juju-log "Installing Composer"
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
sed -i '1i export HOME="/home/ubuntu"' /home/ubuntu/.bashrc
sed -i '2i export PATH="/home/ubuntu/.composer/vendor/bin:$PATH"' /home/ubuntu/.bashrc
source /home/ubuntu/.bashrc

# Drush: install.
juju-log "Installing Drush 6.* with composer"
composer global require drush/drush:6.*

juju-log "So, environment is setup. We'll wait for some hooks to fire off before we get all crazy"